export enum EventType {
  POINTS_MADE = 'POINTS_MADE',
  POINTS_MISSED = 'POINTS_MISSED',
  REBOUND_OFFENSIVE = 'REBOUND_OFFENSIVE',
  REBOUND_DEFENSIVE = 'REBOUND_DEFENSIVE',
  ASSIST = 'ASSIST',
  TURNOVER = 'TURNOVER',
  STEAL = 'STEAL',
  BLOCK = 'BLOCK',
  FOUL_PERSONAL = 'FOUL_PERSONAL',
  FOUL_TECHNICAL = 'FOUL_TECHNICAL',
  FOUL_UNSPORTSMANLIKE = 'FOUL_UNSPORTSMANLIKE',
  FOUL_DISQUALIFYING = 'FOUL_DISQUALIFYING',
  FREE_THROW_AWARDED = 'FREE_THROW_AWARDED',
  SUBSTITUTION = 'SUBSTITUTION',
  TIMEOUT = 'TIMEOUT',
  QUARTER_START = 'QUARTER_START',
  QUARTER_END = 'QUARTER_END',
}

/** Event types that require a playerId */
export const PLAYER_REQUIRED_EVENTS: EventType[] = [
  EventType.POINTS_MADE,
  EventType.POINTS_MISSED,
  EventType.REBOUND_OFFENSIVE,
  EventType.REBOUND_DEFENSIVE,
  EventType.ASSIST,
  EventType.TURNOVER,
  EventType.STEAL,
  EventType.BLOCK,
  EventType.FOUL_PERSONAL,
  EventType.FOUL_TECHNICAL,
  EventType.FOUL_UNSPORTSMANLIKE,
  EventType.FOUL_DISQUALIFYING,
  EventType.FREE_THROW_AWARDED,
  EventType.SUBSTITUTION,
];

/** Event types that are team-level (no player required) */
export const TEAM_LEVEL_EVENTS: EventType[] = [
  EventType.TIMEOUT,
  EventType.QUARTER_START,
  EventType.QUARTER_END,
];
