-- AlterEnum
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'POSTPONED';
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'SUSPENDED';

-- AlterTable
ALTER TABLE "matches"
  ADD COLUMN "totalPeriods" INTEGER NOT NULL DEFAULT 4,
  ADD COLUMN "periodDurationMinutes" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "suspensionReason" TEXT;
